#!/bin/bash

MINIFY_COMMAND="minify"

if ! command -v $MINIFY_COMMAND &> /dev/null;then
    echo "command $MINIFY_COMMAND could not be found"
    exit 1
fi

JSLastModified=$(date -r abbreviation-autocomplete.js +%s)
minifiedJSLastModified=$(date -r abbreviation-autocomplete.min.js +%s)

# Staged files
changed_files=($(git diff --name-only --cached))

for file in "${changed_files[@]}"; do
  if [[ $file == abbreviation-autocomplete.js ]];then
    JSChanged=1
  elif [[ $file == abbreviation-autocomplete.min.js ]];then
    minifiedJSChanged=1
  fi
done

if [[ $JSChanged && ($JSLastModified -gt $minifiedJSLastModified || ! $minifiedJSChanged) ]];then
  if [[ $JSLastModified -gt $minifiedJSLastModified ]]; then
    echo "ERROR: staged minified version is not up to date"
    echo "INFO: Auto minifying"
    npx minify abbreviation-autocomplete.js > abbreviation-autocomplete.min.js
  fi

  echo "ERROR: updated minfied file not stage for commit"
  echo "INFO: Please add abbreviation-autocomplete.min.js and recommit"
  exit 1
elif [[ $JSChanged ]];then 
  echo "INFO: minified js has been modified after original js file and is believed to be up to date"
fi
